version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis:6379
      - SQLITE_PATH=/app/data/db
      - MIGRATION_PATH=migrations/sqlite

    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
