-- DROP INDEX IF EXISTS idx_follows_following;
-- DROP INDEX IF EXISTS idx_follows_followed;
-- DROP INDEX IF EXISTS idx_post_user;
-- DROP INDEX IF EXISTS idx_comment_post;
-- DROP INDEX IF EXISTS idx_comment_user;
-- DROP INDEX IF EXISTS idx_message_chat;
-- DROP INDEX IF EXISTS idx_message_sender;
-- DROP INDEX IF EXISTS idx_message_receiver;

-- -- Consider dropping these performance-improving indexes if they were created:
-- -- DROP INDEX IF EXISTS idx_post_created_at;
-- -- DROP INDEX IF EXISTS idx_message_created_at;